"""Render self-contained HTML reports from a ScanReport / ComparisonReport.

The output is a single .html file with inline CSS (no external assets), so it
opens anywhere and is easy to screenshot for a portfolio. A dark "terminal"
theme is used on purpose.

Security note: every piece of model/attack content is HTML-escaped before it is
embedded. A target's response is untrusted input — it could contain `<script>`
or other markup — and the report must not become an XSS vector when opened in a
browser. This mirrors the prompt-injection-safe stance of the Claude judge.
"""

from __future__ import annotations

from html import escape as esc

from .models import ComparisonReport, ScanReport, Verdict

_VERDICT_LABEL = {
    Verdict.SUCCESS: "SUCCESS",
    Verdict.BLOCKED: "BLOCKED",
    Verdict.PARTIAL: "PARTIAL",
    Verdict.ERROR: "ERROR",
}

# CSS class per verdict, so colors stay consistent between badges and cards.
_VERDICT_CLASS = {
    Verdict.SUCCESS: "bad",
    Verdict.BLOCKED: "good",
    Verdict.PARTIAL: "warn",
    Verdict.ERROR: "muted",
}

_CSS = """
:root {
  --bg: #0d1117; --panel: #161b22; --border: #30363d; --text: #e6edf3;
  --muted: #8b949e; --good: #3fb950; --warn: #d29922; --bad: #f85149;
  --accent: #58a6ff;
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2.5rem 1.25rem; background: var(--bg); color: var(--text);
  font: 15px/1.6 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
}
.wrap { max-width: 980px; margin: 0 auto; }
h1 { font-size: 1.7rem; margin: 0 0 .25rem; }
h2 { font-size: 1.25rem; margin: 2.2rem 0 .8rem; border-bottom: 1px solid var(--border); padding-bottom: .35rem; }
h3 { font-size: 1rem; margin: 0 0 .5rem; font-family: ui-monospace, "Cascadia Code", Consolas, monospace; }
a { color: var(--accent); }
code, .mono { font-family: ui-monospace, "Cascadia Code", Consolas, monospace; }
.meta { color: var(--muted); margin: 0 0 1.5rem; }
.meta b { color: var(--text); }
.scorecard {
  display: flex; align-items: center; gap: 1.5rem; background: var(--panel);
  border: 1px solid var(--border); border-radius: 12px; padding: 1.25rem 1.5rem;
}
.score { font-size: 3rem; font-weight: 700; line-height: 1; }
.score small { font-size: 1rem; color: var(--muted); font-weight: 400; }
.chips { display: flex; flex-wrap: wrap; gap: .5rem; margin: 1rem 0; }
.chip {
  background: var(--panel); border: 1px solid var(--border); border-radius: 999px;
  padding: .25rem .8rem; font-size: .85rem;
}
.good { color: var(--good); } .warn { color: var(--warn); }
.bad { color: var(--bad); } .muted { color: var(--muted); }
table { width: 100%; border-collapse: collapse; margin: .5rem 0 1rem; font-size: .9rem; }
th, td { text-align: left; padding: .5rem .6rem; border-bottom: 1px solid var(--border); }
th { color: var(--muted); font-weight: 600; }
.badge {
  display: inline-block; padding: .1rem .55rem; border-radius: 6px; font-size: .78rem;
  font-weight: 600; border: 1px solid currentColor;
}
.card {
  background: var(--panel); border: 1px solid var(--border); border-left: 4px solid var(--bad);
  border-radius: 10px; padding: 1rem 1.2rem; margin: 1rem 0;
}
.card .label { color: var(--muted); font-size: .8rem; text-transform: uppercase; letter-spacing: .04em; margin-top: .7rem; }
pre {
  background: #0b0f14; border: 1px solid var(--border); border-radius: 8px;
  padding: .8rem; overflow-x: auto; white-space: pre-wrap; word-break: break-word;
  font-family: ui-monospace, "Cascadia Code", Consolas, monospace; font-size: .82rem;
}
.bar { background: #0b0f14; border-radius: 6px; height: 10px; width: 120px; overflow: hidden; display: inline-block; vertical-align: middle; margin-right: .5rem; }
.bar-fill { height: 100%; }
.bar-fill.good { background: var(--good); } .bar-fill.warn { background: var(--warn); } .bar-fill.bad { background: var(--bad); }
footer { color: var(--muted); font-size: .8rem; margin-top: 2.5rem; border-top: 1px solid var(--border); padding-top: 1rem; }
.empty { color: var(--muted); font-style: italic; }
"""


def _score_class(score: float) -> str:
    """green >= 80, amber >= 50, red below."""
    if score >= 80:
        return "good"
    if score >= 50:
        return "warn"
    return "bad"


def _page(title: str, body: str) -> str:
    return (
        "<!doctype html>\n"
        '<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>{esc(title)}</title><style>{_CSS}</style></head>"
        f'<body><div class="wrap">{body}'
        "<footer>Generated by the LLM Robustness Scanner.</footer>"
        "</div></body></html>\n"
    )


def _verdict_badge(verdict: Verdict) -> str:
    cls = _VERDICT_CLASS[verdict]
    return f'<span class="badge {cls}">{_VERDICT_LABEL[verdict]}</span>'


def _excerpt(text: str, limit: int = 1200) -> str:
    text = text.strip()
    return text if len(text) <= limit else text[:limit] + " […]"


def render_html(report: ScanReport) -> str:
    """Render a single scan as a self-contained HTML page."""
    s = report.summary
    cls = _score_class(s.robustness_score)
    parts: list[str] = []

    parts.append(f"<h1>Robustness report — {esc(report.target_name)}</h1>")
    parts.append(
        f'<p class="meta">Target model <b class="mono">{esc(report.model)}</b> · '
        f"{esc(report.started_at)} · {s.total} attacks</p>"
    )

    parts.append(
        '<div class="scorecard">'
        f'<div class="score {cls}">{s.robustness_score}'
        "<small>/100 robustness</small></div>"
        f'<div>Attack success rate: <b class="{cls}">{s.attack_success_rate}%</b>'
        "<br><span class=\"muted\">% of attacks the model withstood</span></div>"
        "</div>"
    )

    parts.append(
        '<div class="chips">'
        f'<span class="chip bad">🔴 {s.success} success</span>'
        f'<span class="chip good">🟢 {s.blocked} blocked</span>'
        f'<span class="chip warn">🟡 {s.partial} partial</span>'
        f'<span class="chip muted">⚪ {s.error} error</span>'
        "</div>"
    )

    parts.append("<h2>Breakdown by category</h2>")
    parts.append(
        "<table><thead><tr><th>Category</th><th>Total</th>"
        "<th>🔴 Success</th><th>🟢 Blocked</th><th>🟡 Partial</th></tr></thead><tbody>"
    )
    for c in s.by_category:
        parts.append(
            f"<tr><td>{esc(c.category)}</td><td>{c.total}</td>"
            f'<td class="bad">{c.success}</td><td class="good">{c.blocked}</td>'
            f'<td class="warn">{c.partial}</td></tr>'
        )
    parts.append("</tbody></table>")

    breaks = [r for r in report.results if r.verdict == Verdict.SUCCESS]
    parts.append(f"<h2>🔴 Attacks that worked ({len(breaks)})</h2>")
    if not breaks:
        parts.append(
            '<p class="empty">None: the model resisted every attack in this run.</p>'
        )
    for r in breaks:
        parts.append(
            '<div class="card">'
            f"<h3>{esc(r.attack.id)} — {esc(r.attack.category)} / "
            f"{esc(r.attack.technique)}</h3>"
            f'<div><b>Goal:</b> {esc(r.attack.goal)}</div>'
            f"<div><b>Verdict:</b> {_verdict_badge(r.verdict)} "
            f"{esc(r.rationale)}</div>"
            '<div class="label">Prompt sent</div>'
            f"<pre>{esc(r.attack.prompt.strip())}</pre>"
            '<div class="label">Model response (truncated)</div>'
            f"<pre>{esc(_excerpt(r.response))}</pre>"
            "</div>"
        )

    parts.append("<h2>Appendix — all results</h2>")
    parts.append(
        "<table><thead><tr><th>Attack</th><th>Category</th><th>Technique</th>"
        "<th>Verdict</th><th>Latency (s)</th></tr></thead><tbody>"
    )
    for r in report.results:
        parts.append(
            f'<tr><td class="mono">{esc(r.attack.id)}</td>'
            f"<td>{esc(r.attack.category)}</td><td>{esc(r.attack.technique)}</td>"
            f"<td>{_verdict_badge(r.verdict)}</td><td>{r.latency_s}</td></tr>"
        )
    parts.append("</tbody></table>")

    return _page(f"Robustness report — {report.target_name}", "".join(parts))


def render_comparison_html(comparison: ComparisonReport) -> str:
    """Render a side-by-side comparison of several models as an HTML page."""
    ranked = sorted(
        comparison.reports,
        key=lambda r: r.summary.robustness_score,
        reverse=True,
    )
    parts: list[str] = []

    parts.append(f"<h1>Model comparison — {esc(comparison.target_name)}</h1>")
    parts.append(
        f'<p class="meta">{esc(comparison.started_at)} · '
        f"{len(ranked)} models · {comparison.attacks_total} attacks each</p>"
    )

    parts.append("<h2>🏆 Leaderboard (most robust first)</h2>")
    parts.append(
        "<table><thead><tr><th>#</th><th>Model</th><th>Robustness</th>"
        "<th>ASR</th><th>🔴</th><th>🟢</th><th>🟡</th><th>⚪</th></tr></thead><tbody>"
    )
    for rank, r in enumerate(ranked, start=1):
        s = r.summary
        cls = _score_class(s.robustness_score)
        bar = (
            f'<span class="bar"><span class="bar-fill {cls}" '
            f'style="width:{s.robustness_score}%"></span></span>'
            f'<b class="{cls}">{s.robustness_score}</b>'
        )
        parts.append(
            f'<tr><td>{rank}</td><td class="mono">{esc(r.model)}</td>'
            f"<td>{bar}</td><td>{s.attack_success_rate}%</td>"
            f'<td class="bad">{s.success}</td><td class="good">{s.blocked}</td>'
            f'<td class="warn">{s.partial}</td><td class="muted">{s.error}</td></tr>'
        )
    parts.append("</tbody></table>")

    categories = sorted(
        {c.category for r in comparison.reports for c in r.summary.by_category}
    )
    parts.append("<h2>Successful attacks by category</h2>")
    parts.append('<p class="meta">Cells show successful attacks / total.</p>')
    head = "".join(f'<th class="mono">{esc(r.model)}</th>' for r in ranked)
    parts.append(f"<table><thead><tr><th>Category</th>{head}</tr></thead><tbody>")
    for cat in categories:
        cells = []
        for r in ranked:
            stat = next(
                (c for c in r.summary.by_category if c.category == cat), None
            )
            if stat:
                hue = "bad" if stat.success else "good"
                cells.append(f'<td class="{hue}">{stat.success}/{stat.total}</td>')
            else:
                cells.append('<td class="muted">—</td>')
        parts.append(f"<tr><td>{esc(cat)}</td>{''.join(cells)}</tr>")
    parts.append("</tbody></table>")

    return _page(f"Model comparison — {comparison.target_name}", "".join(parts))
